// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/login/": {
            "post": {
                "description": "login user with Email, Password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "login for a user",
                "operationId": "user-login",
                "parameters": [
                    {
                        "description": "The input for login for user",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserID"
                        }
                    },
                    "400": {
                        "description": "Invalid data",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "401": {
                        "description": "Email id doesn't exist / Wrong password",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "409": {
                        "description": "This record contains duplicated data that conflicts with what is already in the database",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "498": {
                        "description": "Invalid token",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    }
                }
            }
        },
        "/signup/": {
            "post": {
                "description": "add new user details with Email, FullName, Password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Add a new user",
                "operationId": "user-signup",
                "parameters": [
                    {
                        "description": "The input for add new user",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserSignup"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserID"
                        }
                    },
                    "400": {
                        "description": "Invalid data",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "409": {
                        "description": "This record contains duplicated data that conflicts with what is already in the database",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "498": {
                        "description": "Invalid token",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    }
                }
            }
        },
        "/user/alldetails": {
            "get": {
                "security": [
                    {
                        "UserIDAuth": []
                    }
                ],
                "description": "fetch all details by date",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "fetch all details",
                "operationId": "user-alldetails",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"2024-01-01\"",
                        "description": "date for which want to see details",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AllDetails"
                        }
                    },
                    "400": {
                        "description": "Invalid data",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "498": {
                        "description": "Invalid token",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    }
                }
            }
        },
        "/user/exercise/": {
            "put": {
                "security": [
                    {
                        "UserIDAuth": []
                    }
                ],
                "description": "update exercise details like Duration, ExerciseType, CaloriesBurned",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exercise"
                ],
                "summary": "update exercise details of today",
                "operationId": "user-exercise-update",
                "parameters": [
                    {
                        "description": "The input for update the exercise details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Exercise"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User details Successfully updated",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid data",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "409": {
                        "description": "This record contains duplicated data that conflicts with what is already in the database",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "498": {
                        "description": "Invalid token",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "UserIDAuth": []
                    }
                ],
                "description": "add new exercise details with ExerciseType, Duration, CaloriesBurned, Date(default)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exercise"
                ],
                "summary": "Add a new exercise for today for today",
                "operationId": "user-exercise-add",
                "parameters": [
                    {
                        "description": "The input for add exercise",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Exercise"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User details Successfully added",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid data",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "409": {
                        "description": "This record contains duplicated data that conflicts with what is already in the database",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "498": {
                        "description": "Invalid token",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "UserIDAuth": []
                    }
                ],
                "description": "delete exercise details of today with ExerciseType",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exercise"
                ],
                "summary": "delete exercise details of today",
                "operationId": "user-exercise-delete",
                "parameters": [
                    {
                        "description": "The input for delete exercise",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ExerciseType"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User details Successfully deleted",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid data",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "409": {
                        "description": "This record contains duplicated data that conflicts with what is already in the database",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "498": {
                        "description": "Invalid token",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    }
                }
            }
        },
        "/user/meal/": {
            "put": {
                "security": [
                    {
                        "UserIDAuth": []
                    }
                ],
                "description": "update meal details like Ingredients, MealType, CaloriesConsumed",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Meal"
                ],
                "summary": "update meal details of today",
                "operationId": "user-meal-update",
                "parameters": [
                    {
                        "description": "The input for update the meal details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Meal"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User details Successfully updated",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid data",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "409": {
                        "description": "This record contains duplicated data that conflicts with what is already in the database",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "498": {
                        "description": "Invalid token",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "UserIDAuth": []
                    }
                ],
                "description": "add new meal details with MealType, Ingredients, CaloriesConsumed, Date(default)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Meal"
                ],
                "summary": "Add a new meal details for today",
                "operationId": "user-meal-add",
                "parameters": [
                    {
                        "description": "The input for add meal",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Meal"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User details Successfully added",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid data",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "409": {
                        "description": "This record contains duplicated data that conflicts with what is already in the database",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "498": {
                        "description": "Invalid token",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "UserIDAuth": []
                    }
                ],
                "description": "delete meal details of today with MealType",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Meal"
                ],
                "summary": "delete meal details of today",
                "operationId": "user-meal-delete",
                "parameters": [
                    {
                        "description": "The input for delete meal",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.MealType"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User details Successfully deleted",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid data",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "409": {
                        "description": "This record contains duplicated data that conflicts with what is already in the database",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "498": {
                        "description": "Invalid token",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    }
                }
            }
        },
        "/user/profile/": {
            "put": {
                "security": [
                    {
                        "UserIDAuth": []
                    }
                ],
                "description": "update user profile details like Email, FullName, Age, Gender, Height, Weight, HealthGoal, ProfilePhoto",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserProfile"
                ],
                "summary": "update user profile details",
                "operationId": "user-profile-update",
                "parameters": [
                    {
                        "description": "The input for update the user profile details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Users"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User details Successfully updated",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid data",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "409": {
                        "description": "This record contains duplicated data that conflicts with what is already in the database",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "498": {
                        "description": "Invalid token",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    }
                }
            }
        },
        "/user/water/": {
            "put": {
                "security": [
                    {
                        "UserIDAuth": []
                    }
                ],
                "description": "update daily water details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Water"
                ],
                "summary": "update water details of today",
                "operationId": "user-water-update",
                "parameters": [
                    {
                        "description": "The input for update the water details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Water"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User details Successfully updated",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid data",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "409": {
                        "description": "This record contains duplicated data that conflicts with what is already in the database",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "498": {
                        "description": "Invalid token",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "UserIDAuth": []
                    }
                ],
                "description": "add water details with in WaterIntake(in litre), Date(default)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Water"
                ],
                "summary": "Add water consumption for today",
                "operationId": "user-water-add",
                "parameters": [
                    {
                        "description": "The input for add daily water",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Water"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User details Successfully added",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid data",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "409": {
                        "description": "This record contains duplicated data that conflicts with what is already in the database",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "498": {
                        "description": "Invalid token",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "UserIDAuth": []
                    }
                ],
                "description": "delete water details of today",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Water"
                ],
                "summary": "delete water details of today",
                "operationId": "user-water-delete",
                "responses": {
                    "200": {
                        "description": "User details Successfully deleted",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid data",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "409": {
                        "description": "This record contains duplicated data that conflicts with what is already in the database",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "498": {
                        "description": "Invalid token",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    }
                }
            }
        },
        "/user/weight/": {
            "put": {
                "security": [
                    {
                        "UserIDAuth": []
                    }
                ],
                "description": "update daily weight details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Weight"
                ],
                "summary": "update weight details of today",
                "operationId": "user-weight",
                "parameters": [
                    {
                        "description": "The input for update the weight details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Weight"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User details Successfully updated",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid data",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "409": {
                        "description": "This record contains duplicated data that conflicts with what is already in the database",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "498": {
                        "description": "Invalid token",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "UserIDAuth": []
                    }
                ],
                "description": "add weight details with in DailyWeight(in kg), Date(default)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Weight"
                ],
                "summary": "Add weight for today",
                "operationId": "user-weight-add",
                "parameters": [
                    {
                        "description": "The input for add weight",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Weight"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User details Successfully added",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid data",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "409": {
                        "description": "This record contains duplicated data that conflicts with what is already in the database",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "498": {
                        "description": "Invalid token",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "UserIDAuth": []
                    }
                ],
                "description": "delete weight details of today",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Weight"
                ],
                "summary": "delete weight details of today",
                "operationId": "user-weight-delete",
                "responses": {
                    "200": {
                        "description": "User details Successfully deleted",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid data",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "409": {
                        "description": "This record contains duplicated data that conflicts with what is already in the database",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "498": {
                        "description": "Invalid token",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    }
                }
            }
        },
        "/user/yearly-caloriesburned-details": {
            "get": {
                "security": [
                    {
                        "UserIDAuth": []
                    }
                ],
                "description": "fetch monthly average of calories burned by date",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "fetch monthly average of calories burned",
                "operationId": "user-yearlycaloriesburneddetails",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"2024\"",
                        "description": "year for which want to see details",
                        "name": "year",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.YearlyCaloriesBurned"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid data",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "498": {
                        "description": "Invalid token",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    }
                }
            }
        },
        "/user/yearly-weight-details": {
            "get": {
                "security": [
                    {
                        "UserIDAuth": []
                    }
                ],
                "description": "fetch monthly average of weight by date",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "fetch monthly average of weight",
                "operationId": "user-yearlyweightdetails",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"2024\"",
                        "description": "year for which want to see details",
                        "name": "year",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.YearlyWeight"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid data",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "498": {
                        "description": "Invalid token",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AllDetails": {
            "type": "object",
            "properties": {
                "exerciseDetails": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Exercise"
                    }
                },
                "mealDetails": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Meal"
                    }
                },
                "waterDetails": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Meal"
                    }
                },
                "weightDetails": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Exercise"
                    }
                }
            }
        },
        "models.Exercise": {
            "type": "object",
            "required": [
                "caloriesBurned",
                "duration",
                "exerciseType"
            ],
            "properties": {
                "caloriesBurned": {
                    "type": "number",
                    "maximum": 20000
                },
                "date": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer",
                    "maximum": 1440
                },
                "exerciseType": {
                    "type": "string",
                    "enum": [
                        "weight_lifting",
                        "walking",
                        "running",
                        "gym",
                        "yoga"
                    ]
                }
            }
        },
        "models.ExerciseType": {
            "type": "object",
            "required": [
                "exerciseType"
            ],
            "properties": {
                "exerciseType": {
                    "type": "string",
                    "enum": [
                        "weight_lifting",
                        "walking",
                        "running",
                        "gym",
                        "yoga"
                    ]
                }
            }
        },
        "models.Meal": {
            "type": "object",
            "required": [
                "caloriesConsumed",
                "ingredients",
                "mealType"
            ],
            "properties": {
                "caloriesConsumed": {
                    "type": "number",
                    "maximum": 20000,
                    "minimum": 0
                },
                "date": {
                    "type": "string"
                },
                "ingredients": {
                    "type": "string"
                },
                "mealType": {
                    "type": "string",
                    "enum": [
                        "breakfast",
                        "lunch",
                        "snacks",
                        "dinner"
                    ]
                }
            }
        },
        "models.MealType": {
            "type": "object",
            "required": [
                "mealType"
            ],
            "properties": {
                "mealType": {
                    "type": "string",
                    "enum": [
                        "breakfast",
                        "lunch",
                        "snacks",
                        "dinner"
                    ]
                }
            }
        },
        "models.Message": {
            "type": "object",
            "required": [
                "code",
                "message"
            ],
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.UserID": {
            "type": "object",
            "required": [
                "userId"
            ],
            "properties": {
                "userId": {
                    "type": "string"
                }
            }
        },
        "models.UserLogin": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "models.UserSignup": {
            "type": "object",
            "required": [
                "email",
                "fullName",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "models.Users": {
            "type": "object",
            "required": [
                "age",
                "email",
                "fullName",
                "gender",
                "healthGoal",
                "height",
                "weight"
            ],
            "properties": {
                "age": {
                    "type": "integer",
                    "maximum": 130
                },
                "email": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "gender": {
                    "type": "string",
                    "enum": [
                        "male",
                        "female",
                        "other"
                    ]
                },
                "healthGoal": {
                    "type": "string",
                    "enum": [
                        "weight_loss",
                        "weight_gain",
                        "muscle_building",
                        "maintain_body"
                    ]
                },
                "height": {
                    "type": "number",
                    "maximum": 300,
                    "minimum": 50
                },
                "profilePhoto": {
                    "type": "string"
                },
                "weight": {
                    "type": "number",
                    "maximum": 700,
                    "minimum": 2
                }
            }
        },
        "models.Water": {
            "type": "object",
            "required": [
                "waterIntake"
            ],
            "properties": {
                "date": {
                    "type": "string"
                },
                "waterIntake": {
                    "type": "number",
                    "maximum": 20
                }
            }
        },
        "models.Weight": {
            "type": "object",
            "required": [
                "dailyWeight"
            ],
            "properties": {
                "dailyWeight": {
                    "type": "number",
                    "maximum": 700,
                    "minimum": 2
                },
                "date": {
                    "type": "string"
                }
            }
        },
        "models.YearlyCaloriesBurned": {
            "type": "object",
            "required": [
                "averageMonthlyCaloriesBurned",
                "month"
            ],
            "properties": {
                "averageMonthlyCaloriesBurned": {
                    "type": "number"
                },
                "month": {
                    "type": "integer"
                }
            }
        },
        "models.YearlyWeight": {
            "type": "object",
            "required": [
                "averageMonthlyWeight",
                "month"
            ],
            "properties": {
                "averageMonthlyWeight": {
                    "type": "number"
                },
                "month": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "UserIDAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Fitnesstracker API",
	Description:      "This is a sample Fitnessstracker server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
